

services:
  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwordSegura123
      POSTGRES_DB: optafund
    ports:
      - "127.0.0.1:5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d optafund"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-server:
    build:
      context: .  # << MUDANÇA IMPORTANTE: O contexto é a raiz
      dockerfile: ./apps/api-server/Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: passwordSegura123
      DB_NAME: optafund
      JWT_SECRET: O_MEU_SEGREDO_MUITO_LONGO_E_SEGURO
    depends_on:
      db: # <--- O NOME IMPORTANTE É ESTE
        condition: service_healthy
      redis:
        condition: service_healthy

  data-collector:
    build:
      context: . # << MUDANÇA IMPORTANTE
      dockerfile: ./apps/data-collector/Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: passwordSegura123
      DB_NAME: optafund
    depends_on:
      db: # <--- O NOME IMPORTANTE É ESTE
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build:
      context: . # << MUDANÇA IMPORTANTE
      dockerfile: ./apps/client/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-server

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  postgres_data:
  redis_data: